### ISSUE TITLE
Can't see Hisense SmartTV

### ISSUE THREAD

**Issue by KaltWulx** [benzea/gnome-screencast#29]
I run app with :
`G_MESSAGES_DEBUG=all gnome-screencast`

And show this: [](url)https://pastebin.com/gMZ2scqp
And it doesn't show any video Sink in the GUI. What can i do?
Thanks.

**Comment by benzea** [comment]
Looks like you don't have any P2P device. That probably means your network manager is too old, wifi is disabled or wpa_supplicant compiled without P2P support.

**Comment by ArnoldSchiller** [comment]
After doing a few tests, if the device is not found, I made the experience that a manual push at least made my TV visible again. 
```
wpa_cli -i yourwifiadapter p2p_find
```
If you only have one, it also does 
```
wpa_cli p2p_find
```
However, before you start gnome-network-displays. If gnome-network-displays is already started, there will be a "FAIL" because p2p_find has already been started by the software. Advantage of this, you can also check if the Wifi-Adapter can do p2p, if it can, the answer is "OK".
