### ISSUE TITLE
How to build the package?

### ISSUE THREAD

**Issue by IceM4nn** [benzea/gnome-screencast#38]
How to build the package on debian? I'm new to meson build system. this repo lacks of installation instruction which makes me a bit struggle to build. By reading out quick start on meson, I run:
```
$ cd gnome-network-displays-0.90.0
$ mkdir builddir
$ meson builddir
```
But it seems it has many dependencies problems. and some package not available on apt package management system. Should I install the dependencies one by one what stated on error log of meson build, or does it have other easier method to install and solving all dependencies?

Thanks

**Comment by mckarthik7** [comment]
Yes, you will have to install all dependencies one by one. The exact package name may be different on debian so you will have to search for it either using apt-cache search or just googling it. 
It's also possible that the package may not be available unless you upgrade to the latest distribution, for example for libnm and network manager. In that case you will have to run apt-get dist-upgrade.
I was able to find all dependencies on Ubuntu 19 so I think debian should have all libraries as well.

**Comment by huats** [comment]
I have been able to build it too on Ubuntu 19.04 with a step by step resolving of dependencies.
Since I am new to meson I had to search a bit how to use it.
I ended up by doing :
meson build
cd build
ninja

And then I used ./src/gnome-network-displays
to launch it !

**Comment by miurahr** [comment]
Here is a trial of debianize gnome-network-displays in my PPA project for Ubuntu(bionic).
https://launchpad.net/~miurahr/+archive/ubuntu/wifi-p2p/+sourcepub/10371255/+listing-archive-extra

**Comment by miurahr** [comment]
Now successfully distribute the package for Ubuntu bionic.
https://launchpad.net/~miurahr/+archive/ubuntu/wifi-p2p/

@huats you may be able to use it as start point for porting it on Ubuntu 19.04.

**Comment by benzea** [comment]
Assuming this can be closed then.

**Comment by warrenc5** [comment]
I'm testing with the  WeCast AR1922 v7.10.08 - So far I can't recommend this device.

I'm a moderate programmer and would really appreciate a quick section in the README.md about INSTALLING

This is what I tried..

`uname -a`
> Linux leet 4.19.0-5-amd64 #1 SMP Debian 4.19.37-6 (2019-07-18) x86_64 GNU/Linux

`cat /etc/issue`
> Debian GNU/Linux bullseye/sid 

`lsb_release` -a

> No LSB modules are available.
> Distributor ID: Linuxmint
> Description:    Linux Mint LMDE
> Release:        oldstable-updates
> Codename:       sid


btw I'm using unstable apt sources ..

`sudo apt install meson cmake appstream-util libgstreamer1.0-dev libgstrtspserver-1.0-dev libgtk-3-dev libnm-dev libpulse-mainloop-glib0 libpulse-dev libgstreamer-plugins-base1.0-dev`

`meson build`
`ninja -C build`

Then I got all these errors

> loop initial declarations are only allowed in C99 or C11 mode

The problem here is that for whatever reason, meson is using a C++
compiler 

I edited the build/build.ninja file and added the -std=gnu11 (that's 11 not ll in this font) 

`command = cc -std=gnu11 $ARGS -MD -MQ $out -MF '$DEPFILE' -o $out -c $in`

That compiled and linked

`$./build/src/gnome-network-displays`

That opened a window and gave me an error! I couldn't copy and paste (lame)

>No wifi P2P adaptors found... No usable ... check enabled NetworkManager ... wpa_supplicant 

The console displayed

```

** (gnome-network-displays:31543): WARNING **: 05:53:56.599: Error calling DBus method during Screencast portal initialization: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

** (gnome-network-displays:31543): WARNING **: 05:53:56.599: Error initing screencast portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

** (gnome-network-displays:31543): WARNING **: 05:53:56.599: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!

```

`sudo apt install xdg-desktop-portal xdg-desktop-portal-gtk `
`reboot`

Then running I got
```

** (gnome-network-displays:13281): WARNING **: 06:07:39.302: Error calling DBus method during Screencast portal initialization: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:13281): WARNING **: 06:07:39.302: Error initing screencast portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop

** (gnome-network-displays:13281): WARNING **: 06:07:39.302: Screencasting portal is unavailable! It is required to select the monitor to stream!

** (gnome-network-displays:13281): WARNING **: 06:07:39.302: Falling back to X11! You need to fix your setup to avoid issues (XDG Portals and/or mutter screencasting support)!


```

`sudo apt install flatpak`

Now when I run

`./build/src/gnome-network-displays`

I just get the Wifi network error window

In cmst (my network applet) P2P was OFF

Now when I run I just get the Wifi network error window, I will investigate - but at least I got it running :) 

All the best.

**Comment by myxiaojun** [comment]
> Now successfully distribute the package for Ubuntu bionic.
> https://launchpad.net/~miurahr/+archive/ubuntu/wifi-p2p/
>
 
@miurahr 
is there any  distribute the package for Ubuntu bionic with arm64?

**Comment by miurahr** [comment]
>is there any distribute the package for Ubuntu bionic with arm64?

OK, I've enabled PPA option to build arm64 binary、 and now distribute it.
