### ISSUE TITLE
What would be needed to have wlroots support this?

### ISSUE THREAD

**Issue by Algram** [benzea/gnome-screencast#57]
Hello,

it would be great if you could give some insights on what wlroots (https://github.com/swaywm/wlroots/) would need to do to support the screensharing feature.

As I understand correctly this currently only works on wayland mutter or on X11. So wlroots would implement something to support wlroots wayland. Could you elaborate what exactly that would be?

Thanks!

**Comment by benzea** [comment]
mutter uses a relatively simple DBus interface together with pipewire to stream the frames (and mouse cursor positions these days, but that cannot be consumed by gnome-network-displays yet).

It is probably best to simplify exactly the same interface in wlroots.

https://wiki.gnome.org/Projects/Mutter/RemoteDesktop has some (likely somewhat outdated) information. gnome-network-displays actually uses the corresponding Flatpak portal rather than talking directly to mutter.

**Comment by ammen99** [comment]
I think that Screencast support for https://github.com/emersion/xdg-desktop-portal-wlr is needed. I also think somebody wanted to implement this, but I'm not sure if there has been any progress.

**Comment by benzea** [comment]
Well, more importantly the support in the compositor itself is needed.

Either way, I am fine with answering more questions. But I don't really see anything to do on the gnome-network-displays side for now.

Closing the issue, feel free to reopen/open a new one if something more specific comes up.
