### ISSUE TITLE
Issues initializing PulseAudio

### ISSUE THREAD

**Issue by benzea** [benzea/gnome-screencast#63]
In #62 there are reports that Pulseaudio cannot be initialized properly. This seems a bit odd, and while it may well be a pulseaudio issue, it would probably be good to figure out what is happening there. Maybe we can at least show a better error messages about what is going on.

```
** (gnome-network-displays:22419): DEBUG: 16:03:48.774: NdPulseaudio: PA context went into failed state during init
** (gnome-network-displays:22419): DEBUG: 16:03:48.774: NdPulseaudio: Error querying sink info
```

@ArnoldSchiller, could you check whether you see any error messages from the pulseaudio log?

**Comment by ArnoldSchiller** [comment]
Okay, my bad. Then I realize where the error message comes from. To explain my test setup. Remote display is a DYON Smart 40 PRO. On the TV, "Screencast" must be started for the remote display to work. My first attempts to connect to it were with the laptop. Unfortunately all of them were unsuccessful, because the Wifi card doesn't handle p2p properly. Then I tested with a dusty FoxConn box, where the p2p connections were possible, but did not continue these tests with miracast still took place. 

Then I found this great software here. I never got that far with this software - at least gnome-network-displays streamed successfully. The first successful attempt was now madly logged in from the laptop via ssh -Y as root (no one should not work as root - but well it had happened). 

In the meantime I also understand why this first attempt worked because Root had all rights on the network manager. gnome-network-displays absolutely needs the right to establish a network connection, which normally doesn't work for a normal user via ssh. The error in 62 should result from the fact that I tested again over ssh and then in principle no access to pulseaudio is possible without further ado. 

On the Foxconn which runs under Debian the error does not occur. I have set up a naked user there who does nothing but gnome-network-displays. With this setup, gnome-network-displays got on their noses because this new user wasn't allowed to have his own network connections. gnome-network-displays urgently needs the rights to create its own network connections. For most distributions this should be fixed by adding the user to group netdev. 

The Foxconn-gnd user (gnome-network-displays is too long, if I write nd or gnd then I mean this in the future) has the necessary rights in the meantime and the pulse audio error does not occur there. However, I have never succeeded under this user that his screen appears on the DYON. Here I have the window manager under suspicion, which is currently Gnome under Wayland. But Pulseaudio would be there. Say I'm still playing around to get a working setup.

Maybe it would be useful to have an idea in the program - 'don't have Pulseaudio - ok stream only screen without sound - warning message to user' or something like that. That he can't access Pulseaudio via ssh doesn't surprise me now. What amazes me more is that streaming via the ssh console from a laptop with Foxconn logged in works better than via the Foxconn box itself.

**Comment by benzea** [comment]
> For most distributions this should be fixed by adding the user to group netdev.

That should not be needed in "normal" setups. Because the user will be allowed to modify network connections in most distributions if their session is active. If you are doing things through SSH, then you will run into weird restrictions though.

**Comment by ArnoldSchiller** [comment]
Der normale Nutzer vom "normalen Setup" hatte nur ein dummy-pulseaudio - Ich wollte ein klares Setup ohne Altlasten und machte einfach adduser auf dem Foxconn-Kistchen. Der Vorteil davon war, dass ich danach mit diesem neuen Nutzer 3 Pulseaudio Soundgeräte hatte. Der normale Systembenutzer vom normalen Setup hatte zwar nmcli-Rechte, aber irgendwas stimmt da mit dem Pulseaudio nicht. Adduser fügte aber den neuen Benutzer nicht automatisch zur netdev Gruppe und hatte demzufolge keine Netzwerkrechte. 

Oh Sorry english isn't my language The normal user of the "normal setup" only had a dummy-pulseaudio - I wanted a clear setup without any legacy and just made adduser on the Foxconn box. The advantage of this was that I had 3 Pulseaudio sound devices with this new user. The normal system user of the normal setup had nmcli rights, but something is wrong with the Pulseaudio. Adduser did not automatically add the new user to the netdev group and therefore had no network rights.

**Comment by ArnoldSchiller** [comment]
Something went realy wrong and we can't process that file. Hmpf. Schicke den Dump per Mail

**Comment by benzea** [comment]
Right … without re-reading it all, it seems like it was just a weird situation where PA was not fully available.
