### ISSUE TITLE
Support miracast revision 2 discovery modes (i.e. not WiFi Direct/P2P WiFi)

### ISSUE THREAD

**Issue by atuctuc** [benzea/gnome-screencast#87]
hallo, 
i tried to connect to my qumi beamer. it has an miracast app, that i can start. it works with smartphones. the only problem is, that it does only work in the local wifi network, qumi does not support p2p mode. 

is it possible with gnome-network-displays, to connect directly via ip to a miracast server on the qumi beamer, that is connected to the local wifi-network? 
thanks for help,
anan

**Comment by benzea** [comment]
In principle this is likely to work.

In practice, it needs writing the code to discover the device and connecting to it. Which, to be fair, should be simpler than the existing code for WiFi Direct/P2P WiFi.

Basically, we are looking at mirroring the `nd-dummy-*` files for this protocol (`nd-wfd-p2p-*` is more complicated than required here). If you know how to discover the devices and initiate a connection, then things are likely pretty simple from there.

Note that there is some de-duplication support. One probably needs to decide whether to use this, and whether a P2P connection or AP connection should be preferred (I am tending towards prefering P2P for now because I don't know how reliable we setup a TDLS direct connection, and without that we double the channel utilization).

**Comment by benzea** [comment]
i.e. this will boil down to implementing the relevant connection parts from the Wi-Fi Display 2 specification.

**Comment by atuctuc** [comment]
as i know p2p wifi is more stable, but the qumi beamer supports only AP mode not WiFi Direct/P2P, so there is no choice. 

does anybody has an idea, how to miracast a linux desktop to this kind of devices?

**Comment by joakim-tjernlund** [comment]
> i.e. this will boil down to implementing the relevant connection parts from the Wi-Fi Display 2 specification.

I guess Wi-FI Display 2 is becoming common these days, any plans to impl. that too?

**Comment by benzea** [comment]
> I guess Wi-FI Display 2 is becoming common these days, any plans to impl. that too?

Well, technically WFD revision 2 is a superset of revision 1. But it does have a number of extensions, allowing futher discovery methods and also other protocol extensions.

I don*t currently have plans to work on this though. That said, it should be relatively feasible to add these features.
