### ISSUE TITLE
gitlab.gnome.org

### ISSUE THREAD

**Issue by mcatanzaro** [benzea/gnome-screencast#94]
Please either move this project to gitlab.gnome.org, or else rename it to something that doesn't begin with "gnome-"

**Comment by benrob0329** [comment]
It's a GNOME app, that deals with networked displays. As much as I support self-hosted and alternative platforms, this request feels like it only exists to be able to say that "All GNOME Apps are hosted \<here>" despite the fact that many of them are developed independent of one another and not really under the wing of The GNOME Project as a whole.

I am neither for nor against the actual moving or renaming of this project, but this request to do so seems like an overstep and/or one which lacks explanation (e.g. "Please either move or rename because we're attempting to unify the GNOME platform under one source code hosting website and would like to reduce confusion")

**Comment by mcatanzaro** [comment]
OK: "Please either move or rename because we're attempting to unify the GNOME platform under one source code hosting website and would like to reduce confusion." In particular, it'd be nice if stuff we don't host and don't know about would not use the "gnome-" prefix, as that pretty strongly implies endorsement from GNOME.

**Comment by benzea** [comment]
I tried, I really did. I don't like github. But I never got any proper feedback from GNOME admins nor the Foundation on the matter. Pending on some decisions that never got anywhere.

See https://gitlab.gnome.org/Infrastructure/Infrastructure/issues/121#note_627769, "won't take much longer to finalize" and that was in October.

Said differently, I am happy to move. But right now I consider this in the Foundation's hand to figure out what they want. Until then, I feel like making the point that I want this software to have the GNOME prefix/name.

**Comment by benzea** [comment]
Right, I should also mention:

  https://discourse.gnome.org/t/help-needed-naming-a-new-gnome-initiative/759

And there are probably a few Foundation Board Minutes that mention the existence of the above.
